Diagnose/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.generic import RedirectView
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/',include('home.urls')),
    path('',RedirectView.as_view(url='home/')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='home/password/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="home/password/password_reset_confirm.html"), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='home/password/password_reset_complete.html'), name='password_reset_complete'),      

] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path,include
from . import views

app_name = 'home'

urlpatterns = [
    path('',views.index,name='index'),
    path('user_login/', views.user_login, name='user_login'),
    path('dashboard/',views.dashboard,name='dashboard'),
    path('logout/',views.logout,name='logout'),
    path("password_reset/", views.password_reset_request, name="password_reset"),
    path('register/',views.register,name='register'),
    path('search/',views.search,name='search'),
    path('instant_exam/',views.instant_exam, name='instant_exam'),
    path('vitals/',views.vitals, name='vitals'),
    path('symptoms/',views.symptoms, name='symptoms'),
    path('directory/',views.directory,name='directory'),
    path('display/',views.display,name='display'),
    path('survey/',views.survey,name='survey'),
    path('raise_query/',views.raise_query,name='raise_query'),
    path('profile/',views.profile,name='profile'),
    path('medical/',views.medical,name='medical'),
    
    
 

]

home/models.py
# Create your models here.
from django.db import models
from django.contrib.auth.models import User
# from django.utils.translation import gettext_lazy as _

# Create your models here.
specialization=(('Doctor','Doctor'),('Screener','Screener'),('Sevika','Sevika'),('Ngo','Ngo'),('Pharmacy','Pharmacy'))


class CustomUser(models.Model):
    
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    upload = models.ImageField(upload_to='static/image')
    mobile=models.BigIntegerField(null=True)
    specialization = models.CharField(max_length=30, choices=specialization,blank=True,null=True)
    gender = models.CharField(max_length=6, choices=[('Male','Male'),('Female','Female')])
    qualification= models.CharField(max_length=30, choices=[('No Formal education','No Formal education'),('Primary Education','Primary Educations'),('Secondary Education','Secondary Education'),('Post Graduation diploma','Post Graduation Diploma'),('Vocational Qualification','Vocational Qualification'),('Bachelors Degree','Bachelors Degree'),('Masters Degree','Masters Degree'),('Doctorate or Higher','Doctorate or Higher')],default=None,null=True,blank=True)
    dob=models.DateField()
    blood_grp = models.CharField(max_length=20, choices=[('A+','A+'),('A-','A-'),('B+','B+'),('B-','B-'),('O+','O+'),('O-','O-'),('AB+','AB+'),('AB-','AB-')])
    country=models.CharField(default='India',max_length=10)
    state=models.CharField(max_length=30)
    district=models.CharField(max_length=30)
    address=models.CharField(max_length=100)
    aadhar = models.CharField(max_length=12,unique=True)
    pincode= models.CharField(max_length=6,default='123456')
    
    
    
   



    symptoms = models.CharField(max_length=1000,null=True,blank=True)
    disease=models.CharField(max_length=255,null=True,blank=True)
    height = models.CharField(max_length=10,null=True,blank=True)
    weight = models.CharField(max_length=10,null=True,blank=True)
    bp_sys= models.CharField(max_length=10,null=True,blank=True)
    bp_dia=models.CharField(max_length=10,null=True,blank=True)
    spo2=models.CharField(max_length=10,null=True,blank=True)
    pulse=models.CharField(max_length=10,null=True,blank=True)
    temp=models.CharField(max_length=10,null=True,blank=True)
    arm=models.CharField(max_length=10,null=True,blank=True)
    Issue_no=models.CharField(max_length=20,null=True,blank=True)
    Issue_date=models.CharField(max_length=20,null=True,blank=True)
    subject = models.CharField(max_length=2002,null=True,blank=True)
    issue= models.CharField(max_length=20,null=True,blank=True)




class Survey(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE,max_length=20,null=True,default=None)
    adhar=models.CharField(max_length=12,null=True,blank=True,unique=True)
    no_of_family_members=models.CharField(max_length=20,null=True,blank=True)
    name_of_head_of_family=models.CharField(max_length=20,null=True,blank=True)
    age_of_head_of_family=models.CharField(max_length=20,null=True,blank=True)
    no_of_other_adult_males=models.CharField(max_length=20,null=True,blank=True)
    no_of_other_adult_female=models.CharField(max_length=20,null=True,blank=True)
    no_of_male_children=models.CharField(max_length=20,null=True,blank=True)
    no_of_female_children=models.CharField(max_length=20,null=True,blank=True)
    water_source=models.CharField(max_length=20,null=True,blank=True)
    water_distance=models.CharField(max_length=20,null=True,blank=True)
    water_treatment=models.CharField(max_length=20,null=True,blank=True)
    non_usage_of_toilets=models.CharField(max_length=20,null=True,blank=True)
    distance_of_subcentres=models.CharField(max_length=20,null=True,blank=True)
    distance_of_primary_centers=models.CharField(max_length=20,null=True,blank=True)
    distance_of_community_centers=models.CharField(max_length=20,null=True,blank=True)
    distance_of_district_hospital=models.CharField(max_length=20,null=True,blank=True)
    distance_of_patahology_lab=models.CharField(max_length=20,null=True,blank=True)
    distance_of_medical_store=models.CharField(max_length=20,null=True,blank=True)
    status_of_delivery_of_children=models.CharField(max_length=20,null=True,blank=True)
    status_of_vaccination_of_children=models.CharField(max_length=20,null=True,blank=True)
    status_of_female_problems=models.CharField(max_length=20,null=True,blank=True)
    centrally_issued_health_insurance=models.CharField(max_length=20,null=True,blank=True)
    state_issued_health_insurance=models.CharField(max_length=20,null=True,blank=True)
    personal_health_insurance=models.CharField(max_length=20,null=True,blank=True)

    

home/views.py
import random
from django.shortcuts import render, redirect
from django.contrib.auth.models import auth, User
from django.urls import reverse
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse
from django.contrib.auth.forms import PasswordResetForm
from django.template.loader import render_to_string
from django.db.models.query_utils import Q
from django.utils.http import urlsafe_base64_encode
from django.contrib.auth.tokens import default_token_generator
from django.utils.encoding import force_bytes
from django.contrib import messages
from home.models import CustomUser, Survey
import smtplib
from django.contrib import messages
from django.core.mail import send_mail



# Importing libraries
import numpy as np
import pandas as pd
from scipy.stats import mode
# import matplotlib.pyplot as plt
# import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix
from datetime import date


today=date.today()
d1=today.strftime("%A, %B %d, %Y")


# Create your views here.
def index(request):
    return render(request,'index.html')

def dashboard(request):
	return render(request,'admin_dashboard.html')


def sendEmail(to, content):
    server = smtplib.SMTP('smtp.gmail.com', 587)
    server.ehlo()
    server.starttls()
    server.login('dipakgaikwadmg@gmail.com', 'uhbfgvgbyvmadnvk')
    server.sendmail('dipakgaikwadmg@gmail.com', 'dipakgaikwadmg@gmail.com')
    server.close()

def user_login(request):
    
    if request.method=='POST':
        username=request.POST['username']
        password=request.POST['password']
        user = auth.authenticate(username=username,password=password)
		

        if user is not None:
            auth.login(request,user)
	    	
	    	
	    
	    	
            return redirect(reverse('home:dashboard'))
		
			
	
	

        else:
            print('admin login error')
            return redirect(reverse('home:user_login'))
    else:
        return render(request, 'user_login.html')

def password_reset_request(request):
	if request.method == "POST":
		password_reset_form = PasswordResetForm(request.POST)
		if password_reset_form.is_valid():
			data = password_reset_form.cleaned_data['email']
			associated_users = User.objects.filter(Q(email=data))
			if associated_users.exists():
				for user in associated_users:
					subject = "Password Reset Requested"
					email_template_name = "home/password/password_reset_email.txt"
					c = {
					"email":user.email,
					'domain':'127.0.0.1:8000',
					'site_name': 'Website',
					"uid": urlsafe_base64_encode(force_bytes(user.pk)),
					"user":user,
					'token': default_token_generator.make_token(user),
					'protocol': 'http',
					}
                           
					email = render_to_string(email_template_name, c)
                       
					email = render_to_string(email_template_name, c)
					try:
						send_mail(subject, email, 'dipakgaikwadmg@gmail.com' , [user.email], fail_silently=False)
					except BadHeaderError:
						return HttpResponse('Invalid header found.')
					return redirect ("/password_reset/done/")
	password_reset_form = PasswordResetForm()
	return render(request=request, template_name="home/password/password_reset.html", context={password_reset_form:password_reset_form})


def logout(request):
    auth.logout(request)
    return redirect ('/')



    
    messages.info(request, "You have log in succesfully")
    send_mail(
		'contact form',
		'ti sfd',
		'settings.EMAIL_HOST_USER',s
		['dipakgaikwadmg@gmail.com'],
		
		)
    auth.logout(request)
    return redirect ('/')

def register(request):
	
	if request.method == 'POST':
		first_name = request.POST.get('first_name')
		last_name =request.POST.get('last_name')
		mobile_no =request.POST.get('mobile_no')
		blood_group=request.POST.get('blood_group')
		address =request.POST.get('address')
		gender = request.POST.get('Gender')
		# country = request.POST.get('country')
		state=request.POST.get('state')
		email=request.POST.get('email')
		district=request.POST.get('district')
		dob=request.POST.get('dob')
		adhaar_no=request.POST.get('adhaar_no')
		pincode=request.POST.get('pincode')

		adhar=adhaar_no[-4:]

		username=first_name+last_name+adhar
	

		
		if User.objects.filter(email=email).exists():
			return redirect(reverse('home:register'))
		else:
			user=User.objects.create_user(first_name=first_name,last_name=last_name,email=email,username=username)
			user.save()
			customuser=CustomUser.objects.create(user=user,mobile=mobile_no,blood_grp=blood_group,address=address,gender=gender,state=state,district=district,dob=dob,aadhar=adhaar_no,pincode=pincode)
			customuser.save()
			messages.success(request,"Registration  successful")
			
			print("done")
			
			return redirect(reverse('home:dashboard'))
	else:
			return render(request, 'register.html')
	
def medical(request):
		return render (request,'medical.html')
	


def search(request):
	if request.method == 'POST':
		search = request.POST.get('search')
		user_data=CustomUser.objects.filter(aadhar=search).all()
		return render(request,'search.html',{'user_data':user_data})
	
	
	else:
		return render(request, 'search.html')

def instant_exam(request):
	if request.method == 'POST':
		dob=request.POST.get('dob')
		adhaar_no=request.POST.get('adhaar_no')
		request.session['adhaar_no']=request.POST['adhaar_no']
		if CustomUser.objects.filter(dob=dob,aadhar=adhaar_no).exists():
			obj=CustomUser.objects.filter(dob=dob,aadhar=adhaar_no).all()
			return render(request,'instant_exam/info.html')
		else:
			return redirect(reverse('home:instant_exam'))
	else:
		return render(request,'instant_exam/instant_exam_login.html')

def vitals(request):
	if request.method == 'POST':
		url1=request.session['adhaar_no']
		height=request.POST.get('height')
		weight=request.POST.get('weight')
		bp_sys=request.POST	.get('bp_sys')
		bp_dia=request.POST.get('bp_dia')
		spo2=request.POST.get('spo2')
		pulse=request.POST.get('pulse')
		temp=request.POST.get('temp')
		arm=request.POST.get('arm')

		user_obj=CustomUser.objects.get(aadhar=url1)
		user_obj.height=height
		user_obj.weight=weight
		user_obj.bp_sys=bp_sys
		user_obj.bp_dia=bp_dia
		user_obj.spo2=spo2
		user_obj.pulse=pulse
		user_obj.temp=temp
		user_obj.arm=arm
		user_obj.save()
		print(user_obj)
		return render(request, 'instant_exam/info.html')

	return render(request,'instant_exam/vitals_form.html')

def Issue_No():
    a=random.randint(100000, 1000000)
    today = date.today()
    d = today.strftime("%m%d%Y")
    return str(d)+"-"+str(a)

def Issue_Date():
    today = date.today()
    d1 = today.strftime("%d-%m-%Y")
    return str(d1)



def symptoms(request):
	if request.method=='POST':
		symptoms_txt = request.POST.get('textarea',None)
		url1=request.session['adhaar_no']

		# Reading the train.csv by removing the
        # last column since it's an empty column
		DATA_PATH = "E:\\Diagnose\\csv\\Training.csv"
		data = pd.read_csv(DATA_PATH).dropna(axis = 1)
        
        # Checking whether the dataset is balanced or not
		disease_counts = data["prognosis"].value_counts()
		temp_df = pd.DataFrame({
            "Disease": disease_counts.index,
            "Counts": disease_counts.values
        })

        #Splitting
        # Encoding the target value into numerical
        # value using LabelEncoder
		encoder = LabelEncoder()
		data["prognosis"] = encoder.fit_transform(data["prognosis"])

		X = data.iloc[:,:-1]
		y = data.iloc[:, -1]
		X_train, X_test, y_train, y_test =train_test_split(
        X, y, test_size = 0.2, random_state = 24)

        # Defining scoring metric for k-fold cross validation
		def cv_scoring(estimator, X, y):
			return accuracy_score(y, estimator.predict(X))
        
        # Initializing Models
		models = {
            "SVC":SVC(),
            "Gaussian NB":GaussianNB(),
            "Random Forest":RandomForestClassifier(random_state=18)
        }
        
        # Producing cross validation score for the models
		for model_name in models:
			model = models[model_name]
			scores = cross_val_score(model, X, y, cv = 10,
                                    n_jobs = -1,
                                    scoring = cv_scoring)

        # Training and testing SVM Classifier
		svm_model = SVC()
		svm_model.fit(X_train, y_train)
		preds = svm_model.predict(X_test)
		cf_matrix = confusion_matrix(y_test, preds)

        # Training and testing Naive Bayes Classifier
		nb_model = GaussianNB()
		nb_model.fit(X_train, y_train)
		preds = nb_model.predict(X_test)
		cf_matrix = confusion_matrix(y_test, preds)

        # Training and testing Random Forest Classifier
		rf_model = RandomForestClassifier(random_state=18)
		rf_model.fit(X_train, y_train)
		preds = rf_model.predict(X_test)
		cf_matrix = confusion_matrix(y_test, preds)

        # Training the models on whole data
		final_svm_model = SVC()
		final_nb_model = GaussianNB()
		final_rf_model = RandomForestClassifier(random_state=18)
		final_svm_model.fit(X, y)
		final_nb_model.fit(X, y)
		final_rf_model.fit(X, y)
        
        # Reading the test data
		test_data = pd.read_csv("E:\\Diagnose\\csv\\Testing.csv").dropna(axis=1)
        
		test_X = test_data.iloc[:, :-1]
		test_Y = encoder.transform(test_data.iloc[:, -1])
        
        # Making prediction by take mode of predictions
        # made by all the classifiers
		svm_preds = final_svm_model.predict(test_X)
		nb_preds = final_nb_model.predict(test_X)
		rf_preds = final_rf_model.predict(test_X)
        
		final_preds = [mode([i,j,k])[0][0] for i,j,
                    k in zip(svm_preds, nb_preds, rf_preds)]

		symptoms = X.columns.values
    
        # Creating a symptom index dictionary to encode the
        # input symptoms into numerical form
		symptom_index = {}

home/templates/adminbase.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">

<head>
  <meta charset="utf-8">
  

  <style media="screen">
    a:link {
      text-decoration: none;
    }

    body {
      margin: 0;
      padding: 0;
      font-family: "Gill Sans", sans-serif;;
    }

    header {
      position: fixed;
      background: rgba(28,74,90, 5.0);
      padding: 10px;
      width: 100%;
      z-index: 1;
    }

    .left_area h3 {
      color: #fff;
      margin: 0px;
      text-transform: uppercase;
      font-size: 22px;
      font-weight: 900;
    }

    .left_area span {
      color: #19B3D3;
    }

    .logout_btn {
      padding: 5px;
      background: #19B3D3;
      text-decoration: none;
      float: right;
      margin-top: -30px;
      margin-right: 40px;
      border-radius: 2px;
      font-size: 15px;
      font-weight: 600;
      color: #fff;
      transition: 0.5s;

    }

    .logout_btn:hover {
      background: #0B87A6;
    }

    .sidebar {
      background: #2f323a;
      margin-top: 2000px;
      padding-top: 30px;
      position: fixed;
      left: 0;
      width: 250px;
      height: 100%;
      transition: 0.5s;
      transition-property: left;
    }

    .sidebar .profile_image {
      width: 100px;
      height: 100px;
      border-radius: 100px;
      margin-bottom: 10px;
    }

    .sidebar h4 {
      color: #ccc;
      margin-top: 0;
      margin-bottom: 20px;
    }

    .sidebar a {
      color: #fff;
      display: block;
      width: 100%;
      line-height: 60px;
      text-decoration: none;
      padding-left: 40px;
      box-sizing: border-box;
      transition: 0.5s;

    }

    .sidebar a:hover {
      background: #19B3D3;
    }

    .sidebar i {
      padding-right: 10px;
    }

    label #sidebar_btn {
      z-index: 1;
      color: #fff;
      position: fixed;
      cursor: pointer;
      left: 220px;
      padding-left: 0px;
      font-size: 20px;
      margin: 5px 0;
      transition: 0.5s;
      transition-property: color;
      margin-top: 17px;
    }

    label #sidebar_btn:hover {
      color: #19B3D3;
    }

    #check:checked~.sidebar {
      left: -190px;
    }

    #check:checked~.sidebar a span {
      display: none;
    }

    #check:checked~.sidebar a {
      font-size: 20px;
      margin-left: 170px;
      width: 80px;
    }

    .content {
      margin-left: 250px;
      background: url(background.png) no-repeat;
      background-position: center;
      background-size: cover;
      height: 100vh;
      transition: 0.5s;
    }

    #check:checked~.content {
      margin-left: 60px;
    }

    #check {
      display: none;
    }
  </style>


  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css">


</head>

<body>

  <input type="checkbox" id="check">
  <!--header area start-->
  <header style="padding-top: 0px;">
    <label for="check">
      <i style=""class="fas fa-bars" id="sidebar_btn"></i>
    </label>
    <div class="left_area">
      <a class="navbar-brand" href="#"><img src="{% static 'home/img/logo3.png'%}" class="img-responsive" style="width: 140px; margin-top: -16px;"></a>
    </div>
    <div class="right_area">
      <a href="{% url 'home:logout' %}" class="logout_btn">Logout</a>
    </div>
  </header>
  <!--header area end-->
  <!--sidebar start-->
  <div class="sidebar" style="
    margin-top: 50px;
">
    <center>

      <img src="{% static "image/admin.png" %}" class="profile_image" alt="">
      <h4>{{user.username}}</h4>

    </center>

    <a href="/home/dashboard"><i class="fas fa-tachometer-alt"></i><span>Dashboard</span></a>
    <a href="/home/profile"><i class="fas fa-users"></i><span>Profile</span></a>
     {% comment %} <a href="/home/medical/"><i class="fas fa-list-alt"></i><span>Medical</span></a>{% endcomment %}
    {% comment %} <a href="/admin-policy"><i class="fab fa-product-hunt"></i><span>Policy</span></a> {% endcomment %}
    
    <a href="{% url 'home:logout' %}"><i class="fas fa-sign-out"></i><span>Logout</span></a>


    


  </div>
  <!--sidebar end-->s


  <!--content start-->
  <div class="content">
    <br><br><br><br><br>
    {% block content %}

    {% endblock content %}


    <br><br><br>
 
  </div>
  <!--content end-->
</body>

</html>

home/templates/medical.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">

<head>
  <meta charset="utf-8">
  

  <style media="screen">
    a:link {
      text-decoration: none;
    }

    body {
      margin: 0;
      padding: 0;
      font-family: "Gill Sans", sans-serif;;
    }

    header {
      position: fixed;
      background: rgba(28,74,90, 5.0);
      padding: 10px;
      width: 100%;
      z-index: 1;
    }

    .left_area h3 {
      color: #fff;
      margin: 0px;
      text-transform: uppercase;
      font-size: 22px;
      font-weight: 900;
    }

    .left_area span {
      color: #19B3D3;
    }

    .logout_btn {
      padding: 5px;
      background: #19B3D3;
      text-decoration: none;
      float: right;
      margin-top: -30px;
      margin-right: 40px;
      border-radius: 2px;
      font-size: 15px;
      font-weight: 600;
      color: #fff;
      transition: 0.5s;

    }

    .logout_btn:hover {
      background: #0B87A6;
    }

    .sidebar {
      background: #2f323a;
      margin-top: 2000px;
      padding-top: 30px;
      position: fixed;
      left: 0;
      width: 250px;
      height: 100%;
      transition: 0.5s;
      transition-property: left;
    }

    .sidebar .profile_image {
      width: 100px;
      height: 100px;
      border-radius: 100px;
      margin-bottom: 10px;
    }

    .sidebar h4 {
      color: #ccc;
      margin-top: 0;
      margin-bottom: 20px;
    }

    .sidebar a {
      color: #fff;
      display: block;
      width: 100%;
      line-height: 60px;
      text-decoration: none;
      padding-left: 40px;
      box-sizing: border-box;
      transition: 0.5s;

    }

    .sidebar a:hover {
      background: #19B3D3;
    }

    .sidebar i {
      padding-right: 10px;
    }

    label #sidebar_btn {
      z-index: 1;
      color: #fff;
      position: fixed;
      cursor: pointer;
      left: 220px;
      padding-left: 0px;
      font-size: 20px;
      margin: 5px 0;
      transition: 0.5s;
      transition-property: color;
      margin-top: 17px;
    }

    label #sidebar_btn:hover {
      color: #19B3D3;
    }

    #check:checked~.sidebar {
      left: -190px;
    }

    #check:checked~.sidebar a span {
      display: none;
    }

    #check:checked~.sidebar a {
      font-size: 20px;
      margin-left: 170px;
      width: 80px;
    }

    .content {
      margin-left: 250px;
      background: url(background.png) no-repeat;
      background-position: center;
      background-size: cover;
      height: 100vh;
      transition: 0.5s;
    }

    #check:checked~.content {
      margin-left: 60px;
    }

    #check {
      display: none;
    }
  </style>


  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css">


</head>

<body>

  <input type="checkbox" id="check">
  <!--header area start-->
  <header style="padding-top: 0px;">
    <label for="check">
      <i style=""class="fas fa-bars" id="sidebar_btn"></i>
    </label>
    <div class="left_area">
      <a class="navbar-brand" href="#"><img src="{% static 'home/img/logo3.png'%}" class="img-responsive" style="width: 140px; margin-top: -16px;"></a>
    </div>
    <div class="right_area">
      <a href="{% url 'home:logout' %}" class="logout_btn">Logout</a>
    </div>
  </header>
  <!--header area end-->
  <!--sidebar start-->
  <div class="sidebar" style="
    margin-top: 50px;
">
    <center>

      <img src="{% static "image/admin.png" %}" class="profile_image" alt="">
      <h4>{{user.username}}</h4>
      

    </center>

    <a href="/home/dashboard"><i class="fas fa-tachometer-alt"></i><span>Dashboard</span></a>
    <a href="/home/profile"><i class="fas fa-users"></i><span>Profile</span></a>
     <a href="/home/medical/"><i class="fas fa-list-alt"></i><span>Medical</span></a>
    {% comment %} <a href="/admin-policy"><i class="fab fa-product-hunt"></i><span>Policy</span></a> {% endcomment %}
    
    <a href="{% url 'home:logout' %}"><i class="fas fa-sign-out"></i><span>Logout</span></a>


    


  </div>
  <!--sidebar end-->s


  <!--content start-->
  <div class="content">
    <br><br><br><br><br>
    {% block content %}
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Navbar</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Link</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Dropdown
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="#">Action</a></li>
                  <li><a class="dropdown-item" href="#">Another action</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="#">Something else here</a></li>
                </ul>
              </li>
              <li class="nav-item">
                <a class="nav-link disabled">Disabled</a>
              </li>
            </ul>
            <form class="d-flex" role="search">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
          </div>
        </div>
      </nav>
 
  </div>
  <!--content end-->
</body>

</html>