Diagnose/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.generic import RedirectView
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/',include('home.urls')),
    path('',RedirectView.as_view(url='home/')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='home/password/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="home/password/password_reset_confirm.html"), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='home/password/password_reset_complete.html'), name='password_reset_complete'),      

] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path,include
from . import views

app_name = 'home'

urlpatterns = [
    path('',views.index,name='index'),
    path('user_login/', views.user_login, name='user_login'),
    path('dashboard/',views.dashboard,name='dashboard'),
    path('logout/',views.logout,name='logout'),
    path("password_reset/", views.password_reset_request, name="password_reset"),
    path('register/',views.register,name='register'),
    path('search/',views.search,name='search'),
    path('instant_exam/',views.instant_exam, name='instant_exam'),
    path('vitals/',views.vitals, name='vitals'),
    path('symptoms/',views.symptoms, name='symptoms'),
    path('directory/',views.directory,name='directory'),
    path('display/',views.display,name='display'),
    path('survey/',views.survey,name='survey'),
    path('raise_query/',views.raise_query,name='raise_query'),
    path('profile/',views.profile,name='profile'),
    path('medical/',views.medical,name='medical'),
    
    
 

]

home/models.py
# Create your models here.
from django.db import models
from django.contrib.auth.models import User
# from django.utils.translation import gettext_lazy as _

# Create your models here.
specialization=(('Doctor','Doctor'),('Screener','Screener'),('Sevika','Sevika'),('Ngo','Ngo'),('Pharmacy','Pharmacy'))


class CustomUser(models.Model):
    
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    upload = models.ImageField(upload_to='static/image')
    mobile=models.BigIntegerField(null=True)
    specialization = models.CharField(max_length=30, choices=specialization,blank=True,null=True)
    gender = models.CharField(max_length=6, choices=[('Male','Male'),('Female','Female')])
    qualification= models.CharField(max_length=30, choices=[('No Formal education','No Formal education'),('Primary Education','Primary Educations'),('Secondary Education','Secondary Education'),('Post Graduation diploma','Post Graduation Diploma'),('Vocational Qualification','Vocational Qualification'),('Bachelors Degree','Bachelors Degree'),('Masters Degree','Masters Degree'),('Doctorate or Higher','Doctorate or Higher')],default=None,null=True,blank=True)
    dob=models.DateField()
    blood_grp = models.CharField(max_length=20, choices=[('A+','A+'),('A-','A-'),('B+','B+'),('B-','B-'),('O+','O+'),('O-','O-'),('AB+','AB+'),('AB-','AB-')])
    country=models.CharField(default='India',max_length=10)
    state=models.CharField(max_length=30)
    district=models.CharField(max_length=30)
    address=models.CharField(max_length=100)
    aadhar = models.CharField(max_length=12,unique=True)
    pincode= models.CharField(max_length=6,default='123456')
    
    
    
   



    symptoms = models.CharField(max_length=1000,null=True,blank=True)
    disease=models.CharField(max_length=255,null=True,blank=True)
    height = models.CharField(max_length=10,null=True,blank=True)
    weight = models.CharField(max_length=10,null=True,blank=True)
    bp_sys= models.CharField(max_length=10,null=True,blank=True)
    bp_dia=models.CharField(max_length=10,null=True,blank=True)
    spo2=models.CharField(max_length=10,null=True,blank=True)
    pulse=models.CharField(max_length=10,null=True,blank=True)
    temp=models.CharField(max_length=10,null=True,blank=True)
    arm=models.CharField(max_length=10,null=True,blank=True)
    Issue_no=models.CharField(max_length=20,null=True,blank=True)
    Issue_date=models.CharField(max_length=20,null=True,blank=True)
    subject = models.CharField(max_length=2002,null=True,blank=True)
    issue= models.CharField(max_length=20,null=True,blank=True)




class Survey(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE,max_length=20,null=True,default=None)
    adhar=models.CharField(max_length=12,null=True,blank=True,unique=True)
    no_of_family_members=models.CharField(max_length=20,null=True,blank=True)
    name_of_head_of_family=models.CharField(max_length=20,null=True,blank=True)
    age_of_head_of_family=models.CharField(max_length=20,null=True,blank=True)
    no_of_other_adult_males=models.CharField(max_length=20,null=True,blank=True)
    no_of_other_adult_female=models.CharField(max_length=20,null=True,blank=True)
    no_of_male_children=models.CharField(max_length=20,null=True,blank=True)
    no_of_female_children=models.CharField(max_length=20,null=True,blank=True)
    water_source=models.CharField(max_length=20,null=True,blank=True)
    water_distance=models.CharField(max_length=20,null=True,blank=True)
    water_treatment=models.CharField(max_length=20,null=True,blank=True)
    non_usage_of_toilets=models.CharField(max_length=20,null=True,blank=True)
    distance_of_subcentres=models.CharField(max_length=20,null=True,blank=True)
    distance_of_primary_centers=models.CharField(max_length=20,null=True,blank=True)
    distance_of_community_centers=models.CharField(max_length=20,null=True,blank=True)
    distance_of_district_hospital=models.CharField(max_length=20,null=True,blank=True)
    distance_of_patahology_lab=models.CharField(max_length=20,null=True,blank=True)
    distance_of_medical_store=models.CharField(max_length=20,null=True,blank=True)
    status_of_delivery_of_children=models.CharField(max_length=20,null=True,blank=True)
    status_of_vaccination_of_children=models.CharField(max_length=20,null=True,blank=True)
    status_of_female_problems=models.CharField(max_length=20,null=True,blank=True)
    centrally_issued_health_insurance=models.CharField(max_length=20,null=True,blank=True)
    state_issued_health_insurance=models.CharField(max_length=20,null=True,blank=True)
    personal_health_insurance=models.CharField(max_length=20,null=True,blank=True)

    

home/views.py
import random
from django.shortcuts import render, redirect
from django.contrib.auth.models import auth, User
from django.urls import reverse
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse
from django.contrib.auth.forms import PasswordResetForm
from django.template.loader import render_to_string
from django.db.models.query_utils import Q
from django.utils.http import urlsafe_base64_encode
from django.contrib.auth.tokens import default_token_generator
from django.utils.encoding import force_bytes
from django.contrib import messages
from home.models import CustomUser, Survey
import smtplib
from django.contrib import messages
from django.core.mail import send_mail



# Importing libraries
import numpy as np
import pandas as pd
from scipy.stats import mode
# import matplotlib.pyplot as plt
# import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix
from datetime import date


today=date.today()
d1=today.strftime("%A, %B %d, %Y")


# Create your views here.
def index(request):
    return render(request,'index.html')

def dashboard(request):
	return render(request,'admin_dashboard.html')


def sendEmail(to, content):
    server = smtplib.SMTP('smtp.gmail.com', 587)
    server.ehlo()
    server.starttls()
    server.login('dipakgaikwadmg@gmail.com', 'uhbfgvgbyvmadnvk')
    server.sendmail('dipakgaikwadmg@gmail.com', 'dipakgaikwadmg@gmail.com')
    server.close()

def user_login(request):
    
    if request.method=='POST':
        username=request.POST['username']
        password=request.POST['password']
        user = auth.authenticate(username=username,password=password)
		

        if user is not None:
            auth.login(request,user)
	    	
	    	
	    
	    	
            return redirect(reverse('home:dashboard'))
		
			
	
	

        else:
            print('admin login error')
            return redirect(reverse('home:user_login'))
    else:
        return render(request, 'user_login.html')

def password_reset_request(request):
	if request.method == "POST":
		password_reset_form = PasswordResetForm(request.POST)
		if password_reset_form.is_valid():
			data = password_reset_form.cleaned_data['email']
			associated_users = User.objects.filter(Q(email=data))
			if associated_users.exists():
				for user in associated_users:
					subject = "Password Reset Requested"
					email_template_name = "home/password/password_reset_email.txt"
					c = {
					"email":user.email,
					'domain':'127.0.0.1:8000',
					'site_name': 'Website',
					"uid": urlsafe_base64_encode(force_bytes(user.pk)),
					"user":user,
					'token': default_token_generator.make_token(user),
					'protocol': 'http',
					}
                           
					email = render_to_string(email_template_name, c)
                       
					email = render_to_string(email_template_name, c)
					try:
						send_mail(subject, email, 'dipakgaikwadmg@gmail.com' , [user.email], fail_silently=False)
					except BadHeaderError:
						return HttpResponse('Invalid header found.')
					return redirect ("/password_reset/done/")
	password_reset_form = PasswordResetForm()
	return render(request=request, template_name="home/password/password_reset.html", context={password_reset_form:password_reset_form})


def logout(request):
    auth.logout(request)
    return redirect ('/')



    
    messages.info(request, "You have log in succesfully")
    send_mail(
		'contact form',
		'ti sfd',
		'settings.EMAIL_HOST_USER',s
		['dipakgaikwadmg@gmail.com'],
		
		)
    auth.logout(request)
    return redirect ('/')

def register(request):
	
	if request.method == 'POST':
		first_name = request.POST.get('first_name')
		last_name =request.POST.get('last_name')
		mobile_no =request.POST.get('mobile_no')
		blood_group=request.POST.get('blood_group')
		address =request.POST.get('address')
		gender = request.POST.get('Gender')
		# country = request.POST.get('country')
		state=request.POST.get('state')
		email=request.POST.get('email')
		district=request.POST.get('district')
		dob=request.POST.get('dob')
		adhaar_no=request.POST.get('adhaar_no')
		pincode=request.POST.get('pincode')

		adhar=adhaar_no[-4:]

		username=first_name+last_name+adhar
	

		
		if User.objects.filter(email=email).exists():
			return redirect(reverse('home:register'))
		else:
			user=User.objects.create_user(first_name=first_name,last_name=last_name,email=email,username=username)
			user.save()
			customuser=CustomUser.objects.create(user=user,mobile=mobile_no,blood_grp=blood_group,address=address,gender=gender,state=state,district=district,dob=dob,aadhar=adhaar_no,pincode=pincode)
			customuser.save()
			messages.success(request,"Registration  successful")
			
			print("done")
			
			return redirect(reverse('home:dashboard'))
	else:
			return render(request, 'register.html')
	
def medical(request):
		return render (request,'medical.html')
	


def search(request):
	if request.method == 'POST':
		search = request.POST.get('search')
		user_data=CustomUser.objects.filter(aadhar=search).all()
		return render(request,'search.html',{'user_data':user_data})
	
	
	else:
		return render(request, 'search.html')

def instant_exam(request):
	if request.method == 'POST':
		dob=request.POST.get('dob')
		adhaar_no=request.POST.get('adhaar_no')
		request.session['adhaar_no']=request.POST['adhaar_no']
		if CustomUser.objects.filter(dob=dob,aadhar=adhaar_no).exists():
			obj=CustomUser.objects.filter(dob=dob,aadhar=adhaar_no).all()
			return render(request,'instant_exam/info.html')
		else:
			return redirect(reverse('home:instant_exam'))
	else:
		return render(request,'instant_exam/instant_exam_login.html')

def vitals(request):
	if request.method == 'POST':
		url1=request.session['adhaar_no']
		height=request.POST.get('height')
		weight=request.POST.get('weight')
		bp_sys=request.POST	.get('bp_sys')
		bp_dia=request.POST.get('bp_dia')
		spo2=request.POST.get('spo2')
		pulse=request.POST.get('pulse')
		temp=request.POST.get('temp')
		arm=request.POST.get('arm')

		user_obj=CustomUser.objects.get(aadhar=url1)
		user_obj.height=height
		user_obj.weight=weight
		user_obj.bp_sys=bp_sys
		user_obj.bp_dia=bp_dia
		user_obj.spo2=spo2
		user_obj.pulse=pulse
		user_obj.temp=temp
		user_obj.arm=arm
		user_obj.save()
		print(user_obj)
		return render(request, 'instant_exam/info.html')

	return render(request,'instant_exam/vitals_form.html')

def Issue_No():
    a=random.randint(100000, 1000000)
    today = date.today()
    d = today.strftime("%m%d%Y")
    return str(d)+"-"+str(a)

def Issue_Date():
    today = date.today()
    d1 = today.strftime("%d-%m-%Y")
    return str(d1)



def symptoms(request):
	if request.method=='POST':
		symptoms_txt = request.POST.get('textarea',None)
		url1=request.session['adhaar_no']

		# Reading the train.csv by removing the
        # last column since it's an empty column
		DATA_PATH = "E:\\Diagnose\\csv\\Training.csv"
		data = pd.read_csv(DATA_PATH).dropna(axis = 1)
        
        # Checking whether the dataset is balanced or not
		disease_counts = data["prognosis"].value_counts()
		temp_df = pd.DataFrame({
            "Disease": disease_counts.index,
            "Counts": disease_counts.values
        })

        #Splitting
        # Encoding the target value into numerical
        # value using LabelEncoder
		encoder = LabelEncoder()
		data["prognosis"] = encoder.fit_transform(data["prognosis"])

		X = data.iloc[:,:-1]
		y = data.iloc[:, -1]
		X_train, X_test, y_train, y_test =train_test_split(
        X, y, test_size = 0.2, random_state = 24)

        # Defining scoring metric for k-fold cross validation
		def cv_scoring(estimator, X, y):
			return accuracy_score(y, estimator.predict(X))
        
        # Initializing Models
		models = {
            "SVC":SVC(),
            "Gaussian NB":GaussianNB(),
            "Random Forest":RandomForestClassifier(random_state=18)
        }
        
        # Producing cross validation score for the models
		for model_name in models:
			model = models[model_name]
			scores = cross_val_score(model, X, y, cv = 10,
                                    n_jobs = -1,
                                    scoring = cv_scoring)

        # Training and testing SVM Classifier
		svm_model = SVC()
		svm_model.fit(X_train, y_train)
		preds = svm_model.predict(X_test)
		cf_matrix = confusion_matrix(y_test, preds)

        # Training and testing Naive Bayes Classifier
		nb_model = GaussianNB()
		nb_model.fit(X_train, y_train)
		preds = nb_model.predict(X_test)
		cf_matrix = confusion_matrix(y_test, preds)

        # Training and testing Random Forest Classifier
		rf_model = RandomForestClassifier(random_state=18)
		rf_model.fit(X_train, y_train)
		preds = rf_model.predict(X_test)
		cf_matrix = confusion_matrix(y_test, preds)

        # Training the models on whole data
		final_svm_model = SVC()
		final_nb_model = GaussianNB()
		final_rf_model = RandomForestClassifier(random_state=18)
		final_svm_model.fit(X, y)
		final_nb_model.fit(X, y)
		final_rf_model.fit(X, y)
        
        # Reading the test data
		test_data = pd.read_csv("E:\\Diagnose\\csv\\Testing.csv").dropna(axis=1)
        
		test_X = test_data.iloc[:, :-1]
		test_Y = encoder.transform(test_data.iloc[:, -1])
        
        # Making prediction by take mode of predictions
        # made by all the classifiers
		svm_preds = final_svm_model.predict(test_X)
		nb_preds = final_nb_model.predict(test_X)
		rf_preds = final_rf_model.predict(test_X)
        
		final_preds = [mode([i,j,k])[0][0] for i,j,
                    k in zip(svm_preds, nb_preds, rf_preds)]

		symptoms = X.columns.values
    
        # Creating a symptom index dictionary to encode the
        # input symptoms into numerical form
		symptom_index = {}

home/templates/instant_exam/Report.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Report</title>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'instant_exam/style1.css' %}">
</head>
<body>
    <div class="container bootdey">
        <div class="row invoice row-printable">
            <div class="col-md-10">
                <!-- col-lg-12 start here -->
                <div class="panel panel-default plain" id="dash_0">
                    <!-- Start .panel -->
                    <div class="panel-body p30">
                        <div class="row">
                            <!-- Start .row -->
                            <div class="col-lg-6" style="background-color:black;width:100%;">
                                <!-- col-lg-6 start here -->
                                <div class="invoice-logo"><img width="250" src="{% static 'home/img/logo3.png' %}" alt="Invoice logo"></div>
                            </div>
                            <!-- col-lg-6 end here -->
                            
                            <!-- col-lg-6 end here -->
                            <div class="col-lg-12">
                                <!-- col-lg-12 start here -->
                                <div class="invoice-details mt25">
                                    <br>
                                    <div class="well">
                                        <ul class="list-unstyled mb0">
                                            
                                            <h5>Patient Information</h5>
                                            <li><strong>Name:</strong> {{data.user.first_name}}</li>
                                            <li><strong>Mobile:</strong> {{data.mobile}}</li>
                                            <li><strong>Address:</strong> {{data.address}}</li>
                                            <li><strong>ADHAAR No:</strong> {{data.aadhar}}</li>
                                        </ul>
                                        <hr>
                                    </div>
                                    <div class="well">
                                        <ul class="list-unstyled mb0">
                                            <h5>Extra Information</h5>
                                            <li><strong>Gender:</strong>{{data.gender}}</li>
                                            <li><strong>Date of Birth:</strong>{{data.dob}}</li>
                                            <li><strong>Blood:</strong>{{data.blood_grp}}</li>
                                            <!-- <li><strong>ADHAAR No:</strong> <span class="label label-danger">UNPAID</span></li> -->
                                        </ul>
                                        <hr>
                                    </div>
                                </div>
                             
                                <div class="invoice-items">
                                    <div class="table-responsive" style="overflow: hidden; outline: none;" tabindex="0">
                                        <table class="table table-bordered">
                                            <thead>
                                                <tr>
                                                    <th class="per70 text-center">Vitals Signs</th>
                                                    <!-- <th class="per5 text-center">Qty</th> -->
                                                    <th class="per25 text-center">Figures</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <tr>
                                                    <td>Blood Pressure</td>
                                                    <!-- <td class="text-center">1</td> -->
                                                    <td class="text-center">{{data.bp_sys}}</td>
                                                </tr>
                                                <tr>
                                                    <td>Pulse Rate</td>
                                                    <!-- <td class="text-center">1</td> -->
                                                    <td class="text-center">{{data.pulse}}</td>
                                                </tr>
                                                <tr>
                                                    <td>SPO<sup>2</sup></td>
                                                    <!-- <td class="text-center">12</td> -->
                                                    <td class="text-center">{{data.spo2}}</td>
                                                </tr>
                                                <tr>
                                                    <td>Temperature</td>
                                                    <!-- <td class="text-center">12</td> -->
                                                    <td class="text-center">{{data.temp}}</td>
                                                </tr>
                                                <tr>
                                                    <td>Height</td>
                                                    <!-- <td class="text-center">12</td> -->
                                                    <td class="text-center">{{data.height}}</td>
                                                </tr>
                                                <tr>
                                                    <td>Weight</td>
                                                    <!-- <td class="text-center">12</td> -->
                                                    <td class="text-center">{{data.weight}}</td>
                                                </tr>
                                                <tr>
                                                    <td>Arm Circumference</td>
                                                    <!-- <td class="text-center">12</td> -->
                                                    <td class="text-center">{{data.arm}}</td>
                                                </tr>
                                              
                                        </table>
                                        <h5><strong> Symptoms Information</strong></h5>
                                        <h6>{{symp}}</h6>
                                            <br>
                                        <h3>Result: {{result.final_prediction}}</h3>
                                    </div>
                                    <h5><a href="">Back</a></h5>     
            </div>               
                                </div><button onclick="window.print()">Print</button>
                                <div class="invoice-footer mt25">
                                    <p class="text-center">Generated on {{date}} </p>
                                </div>
                                
                            </div>     
                            <!-- col-lg-12 end here -->
                        </div>
                        <!-- End .row -->
                    </div>
                </div>
                <!-- End .panel -->
            </div>
            <!-- col-lg-12 end here -->
        </div>
        </div>
</body>
</html>

home/templates/instant_exam/info.html
{% load static %}
{% comment %} 

    <li>
        <a href="{% url 'instant_exam:vitals' %}">vitals</a>
    </li>
    <li>
         <a href="{% url 'instant_exam:symptoms' %}">symptoms</a>
    </li>
    <!-- {% comment %}<li>
        <a href="{% url 'instant_exam:history' %}">Create Teacher</a>
    </li>
    <li>
        <a href="{% url 'instant_exam:test_report' %}">List of Teachers</a>
    </li> {% endcomment %} 

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Instant Exam</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'instant_exam/assets/vendor/aos/aos.css' %}" rel="stylesheet">
  <link href="{% static 'instant_exam/assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'instant_exam/assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'instant_exam/assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'instant_exam/assets/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
  <link href="{% static 'instant_exam/assets/vendor/remixicon/remixicon.css' %}" rel="stylesheet">
  <link href="{% static 'instant_exam/assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static 'instant_exam/assets/css/style.css' %}" rel="stylesheet">

  <!-- =======================================================
  * Template Name: Gp - v4.7.0
  * Template URL: https://bootstrapmade.com/gp-free-multipurpose-html-bootstrap-template/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->

  <link rel="stylesheet" type="text/css" href="{% static 'home/css/font-awesome.min.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'home/css/bootstrap.min.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'home/css/style.css' %}">
</head>

<body>
  <!-- ======= Hero Section ======= -->
  <section id="hero" class="d-flex align-items-center justify-content-center">
    <div class="container" data-aos="fade-up">

      <div class="row justify-content-center" data-aos="fade-up" data-aos-delay="150">
        <div class="col-xl-6 col-lg-8">
          <h1>Examination<span>.</span></h1>
          {% comment %} <h2>We are team of talented digital marketers</h2> {% endcomment %}
        </div>
      </div>

      <div class="row gy-4 mt-5 justify-content-center" data-aos="zoom-in" data-aos-delay="250">
        <div class="col-xl-2 col-md-4">
          <div class="icon-box">
            <i class="ri-store-line"></i>
            <h3><a href="{% url 'home:vitals' %}">Vitals</a></h3>
          </div>
        </div>
        <div class="col-xl-2 col-md-4">
          <div class="icon-box">
            <i class="ri-bar-chart-box-line"></i>
            <h3><a href="{% url 'home:symptoms' %}">Symptomps</a></h3>
          </div>
        </div>
        {% comment %} <div class="col-xl-2 col-md-4">
          <div class="icon-box">
            <i class="ri-calendar-todo-line"></i>
            <h3><a href="">History</a></h3>
          </div>
        </div> 
        <div class="col-xl-2 col-md-4">
          <div class="icon-box">
            <i class="ri-paint-brush-line"></i>
            <h3><a href="">Test Reports</a></h3>
          </div>
        </div>{% endcomment %}
        <div class="col-xl-2 col-md-4">
          <div class="icon-box">
            <i class="ri-database-2-line"></i>
            <h3><a href="">Back to the Log in</a></h3>
          </div>
        </div>
      </div>

    </div>
  </section><!-- End Hero -->

  <div id="preloader"></div>
  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="{% static 'instant_exam/assets/vendor/purecounter/purecounter.js' %}"></script>
  <script src="{% static 'instant_exam/assets/vendor/aos/aos.js' %}"></script>
  <script src="{% static 'instant_exam/assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}' %}"></script>
  <script src="{% static 'instant_exam/assets/vendor/glightbox/js/glightbox.min.js' %}"></script>
  <script src="{% static 'instant_exam/assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
  <script src="{% static 'instant_exam/assets/vendor/swiper/swiper-bundle.min.js' %}"></script>
  <script src="{% static 'instant_exam/assets/vendor/php-email-form/validate.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'instant_exam/assets/js/main.js' %}"></script>

</body>

</html>